/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    `kotlin-dsl`

    id("org.hibernate.build.maven-repo-auth") version "3.0.4"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.freefair.lombok") version "8.6"
}

repositories {
    gradlePluginPortal()
    mavenCentral()

    maven {
        name = "space-maven"
        url = uri("https://packages.slne.dev/maven/p/surf/maven")
    }

    maven {
        name = "codemc-releases"
        url = uri("https://repo.codemc.io/repository/maven-releases/")
    }
    
    maven("https://libraries.minecraft.net")
}

configurations.all {
    resolutionStrategy {
        cacheChangingModulesFor(0, "seconds")
    }
}

dependencies {
    api(libs.dev.slne.surf.surf.api.core.api)
    api(libs.net.dv8tion.jda) {
        isChanging = true
        exclude(group = "org.slf4j", module = "slf4j-api")
        exclude(group = "ch.qos.logback", module = "logback-classic")
        exclude(group = "ch.qos.logback", module = "logback-core")
    }
    api(libs.dev.slne.surf.data.core) {
        exclude(group = "org.slf4j", module = "slf4j-api")
        exclude(group = "ch.qos.logback", module = "logback-classic")
        exclude(group = "ch.qos.logback", module = "logback-core")
    }
    api(libs.club.minnced.discord.webhooks) {
        exclude(group = "org.slf4j", module = "slf4j-api")
        exclude(group = "ch.qos.logback", module = "logback-classic")
        exclude(group = "ch.qos.logback", module = "logback-core")
    }
}

group = "dev.slne"
version = "2.0-SNAPSHOT"
description = "surf-discord"

java {
    withJavadocJar()
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
}

publishing {
    repositories {
        maven {
            name = "space-maven"
            url = uri("https://packages.slne.dev/maven/p/surf/maven")
        }
    }

    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
tasks {
    compileJava {
        options.encoding = Charsets.UTF_8.name()
        options.compilerArgs.add("-parameters")
    }
    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }
}
