/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`

    id("org.hibernate.build.maven-repo-auth") version "3.0.4"
    id("com.gradleup.shadow") version "8.3.3"

    kotlin("jvm") version "2.0.20"
    kotlin("plugin.spring") version "1.9.25"
    application
}

repositories {
    gradlePluginPortal()
    mavenCentral()

    maven("https://repo.slne.dev/repository/maven-public/") { name = "maven-public" }
    maven("https://repo.slne.dev/repository/maven-snapshots/") { name = "maven-snapshots" }
    maven("https://repo.slne.dev/repository/maven-proxy/") { name = "maven-proxy" }
}

configurations.all {
    resolutionStrategy {
        cacheChangingModulesFor(0, "seconds")
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:5.0.1")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.apache.commons:commons-lang3:3.17.0")
    implementation("net.kyori:adventure-api:4.17.0")
    implementation("net.kyori:adventure-text-logger-slf4j:4.17.0")
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")
    implementation("com.github.ben-manes.caffeine:caffeine:3.1.8")
    implementation("ch.qos.logback:logback-classic:1.5.6")

    implementation(libs.fastutil)
    implementation(libs.configurate.yaml)
    implementation(libs.configurate.jackson)
    implementation(libs.net.dv8tion.jda) {
        isChanging = true
    }
    implementation(libs.kotlin.coroutines)
    implementation(libs.jda.ktx)
}

group = "dev.slne"
version = "5.0.0-SNAPSHOT"
description = "surf-discord"

java {
    withJavadocJar()
    withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

publishing {
    repositories {
        maven("https://repo.slne.dev/repository/maven-snapshots/") { name = "maven-snapshots" }
    }

    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}


application {
    mainClass.set("dev.slne.discord.BootstrapKt")
}

tasks {
    compileJava {
        options.encoding = Charsets.UTF_8.name()
        options.compilerArgs.add("-parameters")
    }

    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }

    shadowJar {
        archiveFileName.set("bot.jar")
    }
}

tasks.named<Jar>("jar") {
    archiveFileName.set("bot.jar")
}

tasks.withType<Zip> {
    isZip64 = true
}