connect-twitch.de.question=Wie verknüpfe ich meinen Twitch Account mit Discord?
connect-twitch.de.long=Eine Anleitung, wie du deinen Twitch Account mit Discord verknüpfen kannst, findest du hier: [Anleitung](https://docs.castcrafter.de/faq.html#link-twitch)
banned.de.question=Ich wurde gebannt. Was kann ich tun?
banned.de.long=Wenn du denkst, dir ist mit einem Ausschluss vom Server unrecht getan, erstelle einen [Entbannungsantrag](https://docs.castcrafter.de/support#unban-ticket)!
next-event.de.question=Wann findet das nächste Event statt?
next-event.de.long=Wenn ein Event geplant ist, wird dies im Discord unter https://discord.com/channels/133198459531558912/980810495877607524 oder durch CastCrafter im Stream angekündigt.
how-to-open-ticket.de.question=Wie erstelle ich ein Ticket?
how-to-open-ticket.de.long=Eine Anleitung, wie du ein Ticket erstellen kannst, findest du hier: [Anleitung](https://docs.castcrafter.de/support.html)
rulebook.de.question=Regelwerk
rulebook.de.long=Alle Regeln, die auf dem Server gelten, findest du hier: \
  [Regelwerk](https://docs.castcrafter.de/rules)\n\n\
  Bitte lies die Regeln sorgfältig durch, um sicherzustellen, dass alle Mitglieder eine positive Erfahrung haben.\n\n\
  -# Bei Events **können** die Regeln abweichen. \
  Diese Änderungen findest du auf der jeweiligen Event-Seite in der Dokumentation.
server-modpack.de.question=Offizielles Server Modpack
server-modpack.de.long=Um das Spielerlebnis auf dem Server zu optimieren \
  gibt es ein offizielles Modpack, welches ausschließlich getestete Modifikationen enthält. \
  Alle enthaltenen Mods sind erlaubt und mit dem Server kompatibel.\n\
  **Das Modpack könnt ihr auf [Modrinth](https://modrinth.com/modpack/castcrafter-survival-server) herunterladen.**\n\n\
  -# **Änderungen am Modpack oder das Hinzufügen zusätzlicher Mods können zu Inkompatibilitäten und \
  unter Umständen zu einem Ausschluss des Servers führen. \
  Wir übernehmen keine Verantwortung für modifizierte Versionen des Modpacks.**
problem-resourcepack.de.question=Probleme mit dem Ressourcenpaket
problem-resourcepack.de.long=Das Ressourcenpaket läd nicht richtig oder du \
  erhältst dauerhaft die Nachricht `Aktiviere Ressourcenpaket...`?\n\
  Hier findest du eine Anleitung, wie du das Problem beheben kannst: \
  [Anleitung](https://docs.castcrafter.de/troubleshooting.html#resourcepack-issues)
problem-chat.de.question=Probleme mit dem Chat
problem-chat.de.long=Du hast Probleme mit dem Chat, Nachrichten werden nicht gesendet oder du erhältst die Meldung \
  `Der Chat wurde aufgrund eines fehlenden öffentlichen Profilschlüssels deaktiviert`?\n\
  Hier findest du eine Anleitung, wie du das Problem beheben kannst: \
  [Anleitung](https://docs.castcrafter.de/troubleshooting.html#chat-issues)
problem-nrc-voice-chat.de.question=Probleme mit dem NoRisk Client Voice Chat
problem-nrc-voice-chat.de.long=Du hast Probleme mit dem NoRisk Client Voice Chat, weil er sich nicht verbindet?\n\
Hier findest du eine Anleitung, wie du das Problem beheben kannst: \
  [Anleitung](https://docs.castcrafter.de/troubleshooting.html#nrc-voicechat-issues)
problem-connection.de.question=Verbindungsprobleme / Netzwerk Lags
problem-connection.de.long=Du kannst dich nicht mit dem Server verbinden, \
  wirst wegen `Unstable Connection` vom Server geworfen oder hast regelmäßig starke Lags?\n\
  Hier findet du eine Anleitung, wie du das Problem beheben kannst: \
  [Anleitung](https://docs.castcrafter.de/troubleshooting.html#connection-issues)
read-the-docs.de.question=Dokumentation
read-the-docs.de.long=Diese und weitere Fragen werden in unserer ausführlichen \
  Dokumentation beantwortet: [Dokumentation](https://docs.castcrafter.de/community-server-landing-page)\n\n\
  Für detaillierte Anleitungen, Tipps und häufig gestellte Fragen besuche den obigen Link.
maintenance.de.question=Wartungsarbeiten am Netzwerk
maintenance.de.long=Aktuell finden Wartungsarbeiten am gesamten Netzwerk statt. \
  Bitte habe Geduld. Weitere Informationen findest du unter https://discord.com/channels/133198459531558912/980810495877607524
how-to-share-log.de.question=Wie teile ich meinen Log?
how-to-share-log.de.long=Eine Anleitung, wie du deinen Log teilst, findest du hier: [Anleitung](https://docs.castcrafter.de/faq#find-minecraft-log)
clan-info.de.question=Clan-Informationen
clan-info.de.long=Du suchst den Besitzer eines Clans oder möchtest mehr über einen Clan erfahren? \
  [Hier](https://docs.castcrafter.de/clan-more-info.html) findest du eine Übersicht mit zusätzlichen Informationen.
take-part-in-event.de.question=Wie kann ich an einem Event teilnehmen?
take-part-in-event.de.long=[Hier](https://docs.castcrafter.de/how-to-take-part-in-an-event.html) findest du eine Anleitung zur Teilnahme an einem Event.
how-to-join.de.question=Wie kannst du den CastCrafter-Server betreten?
how-to-join.de.long=Möchtest du Teil unserer Community werden? Hier ist eine einfache Anleitung, wie du dem Server beitreten kannst:\n\
  - Schau dir unsere Anleitung hier an: [Anleitung zum Beitreten](https://docs.castcrafter.de/how-to-join)\n\
  - Du brauchst keine Whitelist für den Event-Server.\n\
  - Für den Survival-Server brauchst du eine Whitelist.\n\n\
   -# Wir freuen uns, dich bald auf dem Server zu sehen!
ask.de.question=Frag einfach direkt.
ask.de.long=Wenn du eine Frage hast, stell sie einfach. Suche nicht nach bestimmten Personen oder Experten. Frage nicht, ob du eine Frage stellen darfst oder ob jemand wach oder verfügbar ist. Stell deine Frage direkt im Kanal und warte geduldig auf eine Antwort.
missing-information.de.question=Fehlende Informationen
missing-information.de.long=Uns fehlen aktuell noch einige wichtige Informationen, um dein Anliegen bearbeiten zu können.\n\n\
Bitte überprüfe noch einmal, ob du uns alle wichtigen Informationen mitgeteilt hast:\n\n\
• **Server**, auf dem es aufgetreten ist\n\
• **Koordinaten** (z. B. `110 64 60`)\n\
• **Dimension** (z. B. `Overworld`)\n\
• **Eine genaue Beschreibung des Problems**\n\
• **Zeitraumangabe** (z. B. `Gestern 12:30 Uhr bis 13:30 Uhr`)
how-to-whitelist.de.question=Wie werde ich gewhitelisted?
how-to-whitelist.de.long=Um auf dem Survival-Server spielen zu können, brauchst du anstatt einer Whitelist,\neine aktive Discord-Minecraft Verbindung. Diese kannst du auf https://auth.castcrafter.de/account?tab=accounts einrichten.\n\nSobald sowohl dein Discord- als auch dein Minecraft-Account verknüpft sind,\nkannst du den Survival-Server betreten. Dein Whiteliststatus kannst du im \n<#1124438644523012234> Kanal über den Button **Whitelist überprüfen** einsehen.
ping-pong.de.question=Antwortzeiten & Pings – das solltet ihr wissen!
ping-pong.de.long=Warum antwortet das Serverteam nicht sofort?\n\
  - Das Serverteam arbeitet ehrenamtlich in seiner Freizeit.\n\
  - Wir bemühen uns, bei Problemen und Anliegen so schnell wie möglich zu helfen.\n\
  - Pings sind nicht notwendig – das Team sieht alle Nachrichten und Tickets.\n\
  - Pings beschleunigen nichts, sie können die Bearbeitung sogar verzögern.\n\
  - Bitte habt etwas Geduld und wartet auf eine Antwort.\n\n\
  Vielen Dank für euer Verständnis und eure Rücksichtnahme.

connect-twitch.de.short=Eine Anleitung zum Verknüpfen deines Twitch Accounts mit Discord findest du hier: https://docs.castcrafter.de/faq.html#link-twitch
connect-twitch.en.question=How do I link my Twitch account with Discord?
connect-twitch.en.long=You can find a guide on how to link your Twitch account with Discord here: [Guide](https://docs.castcrafter.de/faq.html#link-twitch)
connect-twitch.en.short=You can find a guide on linking your Twitch account with Discord here: https://docs.castcrafter.de/faq.html#link-twitch

banned.de.short=Wenn du denkst, dein Bann war unberechtigt, erstelle einen Entbannungsantrag: https://docs.castcrafter.de/support#unban-ticket
banned.en.question=I got banned. What can I do?
banned.en.long=If you think your exclusion from the server was unjustified, create an [unban request](https://docs.castcrafter.de/support#unban-ticket)!
banned.en.short=If you think your ban was unjustified, create an unban request: https://docs.castcrafter.de/support#unban-ticket

next-event.de.short=Geplante Events werden im Discord im Ankündigungskanal oder von CastCrafter im Stream angekündigt.
next-event.en.question=When is the next event?
next-event.en.long=If an event is planned, it will be announced on Discord in https://discord.com/channels/133198459531558912/980810495877607524 or by CastCrafter on stream.
next-event.en.short=Planned events are announced in the Discord announcement channel or by CastCrafter on stream.

how-to-open-ticket.de.short=Eine Anleitung zum Erstellen eines Tickets findest du hier: https://docs.castcrafter.de/support.html
how-to-open-ticket.en.question=How do I create a ticket?
how-to-open-ticket.en.long=You can find a guide on how to create a ticket here: [Guide](https://docs.castcrafter.de/support.html)
how-to-open-ticket.en.short=You can find a guide on creating a ticket here: https://docs.castcrafter.de/support.html

rulebook.de.short=Alle Regeln des Servers findest du hier: https://docs.castcrafter.de/rules (bei Events können die Regeln abweichen)
rulebook.en.question=Rules
rulebook.en.long=You can find all rules that apply on the server here: \
  [Rules](https://docs.castcrafter.de/rules)\n\n\
  Please read the rules carefully to make sure every member has a positive experience.\n\n\
  -# During events, the rules **may** differ. \
  You can find these changes on the respective event page in the documentation.
rulebook.en.short=You can find all server rules here: https://docs.castcrafter.de/rules (rules may differ during events)

server-modpack.de.short=Das offizielle Server Modpack mit allen erlaubten Mods findest du auf Modrinth: https://modrinth.com/modpack/castcrafter-survival-server
server-modpack.en.question=Official server modpack
server-modpack.en.long=To optimize the gameplay experience on the server \
  there is an official modpack that only contains tested modifications. \
  All included mods are allowed and compatible with the server.\n\
  **You can download the modpack on [Modrinth](https://modrinth.com/modpack/castcrafter-survival-server).**\n\n\
  -# **Changing the modpack or adding additional mods can lead to incompatibilities and \
  in some cases to an exclusion from the server. \
  We take no responsibility for modified versions of the modpack.**
server-modpack.en.short=You can find the official server modpack with all allowed mods on Modrinth: https://modrinth.com/modpack/castcrafter-survival-server

problem-resourcepack.de.short=Probleme mit dem Ressourcenpaket? Hier findest du eine Anleitung: https://docs.castcrafter.de/troubleshooting.html#resourcepack-issues
problem-resourcepack.en.question=Problems with the resource pack
problem-resourcepack.en.long=The resource pack does not load correctly or you \
  keep getting the message `Activating resource pack...`?\n\
  You can find a guide on how to fix the problem here: \
  [Guide](https://docs.castcrafter.de/troubleshooting.html#resourcepack-issues)
problem-resourcepack.en.short=Problems with the resource pack? You can find a guide here: https://docs.castcrafter.de/troubleshooting.html#resourcepack-issues

problem-chat.de.short=Probleme mit dem Chat? Hier findest du eine Anleitung: https://docs.castcrafter.de/troubleshooting.html#chat-issues
problem-chat.en.question=Problems with the chat
problem-chat.en.long=You have problems with the chat, messages are not sent or you get the message \
  `Chat disabled due to missing profile public key`?\n\
  You can find a guide on how to fix the problem here: \
  [Guide](https://docs.castcrafter.de/troubleshooting.html#chat-issues)
problem-chat.en.short=Problems with the chat? You can find a guide here: https://docs.castcrafter.de/troubleshooting.html#chat-issues

problem-nrc-voice-chat.de.short=Der NoRisk Client Voice Chat verbindet sich nicht? Hier findest du eine Anleitung: https://docs.castcrafter.de/troubleshooting.html#nrc-voicechat-issues
problem-nrc-voice-chat.en.question=Problems with the NoRisk Client voice chat
problem-nrc-voice-chat.en.long=You have problems with the NoRisk Client voice chat because it does not connect?\n\
  You can find a guide on how to fix the problem here: \
  [Guide](https://docs.castcrafter.de/troubleshooting.html#nrc-voicechat-issues)
problem-nrc-voice-chat.en.short=The NoRisk Client voice chat does not connect? You can find a guide here: https://docs.castcrafter.de/troubleshooting.html#nrc-voicechat-issues

problem-connection.de.short=Verbindungsprobleme oder Lags? Hier findest du eine Anleitung: https://docs.castcrafter.de/troubleshooting.html#connection-issues
problem-connection.en.question=Connection problems / network lag
problem-connection.en.long=You cannot connect to the server, \
  get kicked from the server because of `Unstable Connection` or regularly have heavy lag?\n\
  You can find a guide on how to fix the problem here: \
  [Guide](https://docs.castcrafter.de/troubleshooting.html#connection-issues)
problem-connection.en.short=Connection problems or lag? You can find a guide here: https://docs.castcrafter.de/troubleshooting.html#connection-issues

read-the-docs.de.short=Diese und weitere Fragen beantwortet unsere Dokumentation: https://docs.castcrafter.de/community-server-landing-page
read-the-docs.en.question=Documentation
read-the-docs.en.long=These and other questions are answered in our detailed \
  documentation: [Documentation](https://docs.castcrafter.de/community-server-landing-page)\n\n\
  For detailed guides, tips and frequently asked questions, visit the link above.
read-the-docs.en.short=These and other questions are answered in our documentation: https://docs.castcrafter.de/community-server-landing-page

maintenance.de.short=Aktuell finden Wartungsarbeiten am Netzwerk statt. Weitere Informationen findest du im Discord.
maintenance.en.question=Network maintenance
maintenance.en.long=Maintenance is currently taking place on the entire network. \
  Please be patient. You can find more information at https://discord.com/channels/133198459531558912/980810495877607524
maintenance.en.short=Maintenance is currently taking place on the network. You can find more information on Discord.

how-to-share-log.de.short=Eine Anleitung zum Teilen deines Logs findest du hier: https://docs.castcrafter.de/faq#find-minecraft-log
how-to-share-log.en.question=How do I share my log?
how-to-share-log.en.long=You can find a guide on how to share your log here: [Guide](https://docs.castcrafter.de/faq#find-minecraft-log)
how-to-share-log.en.short=You can find a guide on sharing your log here: https://docs.castcrafter.de/faq#find-minecraft-log

clan-info.de.short=Informationen zu Clans und ihren Besitzern findest du hier: https://docs.castcrafter.de/clan-more-info.html
clan-info.en.question=Clan information
clan-info.en.long=Are you looking for the owner of a clan or do you want to learn more about a clan? \
  [Here](https://docs.castcrafter.de/clan-more-info.html) you can find an overview with additional information.
clan-info.en.short=You can find information about clans and their owners here: https://docs.castcrafter.de/clan-more-info.html

take-part-in-event.de.short=Eine Anleitung zur Teilnahme an einem Event findest du hier: https://docs.castcrafter.de/how-to-take-part-in-an-event.html
take-part-in-event.en.question=How can I take part in an event?
take-part-in-event.en.long=[Here](https://docs.castcrafter.de/how-to-take-part-in-an-event.html) you can find a guide on how to take part in an event.
take-part-in-event.en.short=You can find a guide on taking part in an event here: https://docs.castcrafter.de/how-to-take-part-in-an-event.html

how-to-join.de.short=Eine Anleitung zum Beitreten findest du hier: https://docs.castcrafter.de/how-to-join (Event-Server ohne Whitelist, Survival-Server mit Whitelist)
how-to-join.en.question=How can you join the CastCrafter server?
how-to-join.en.long=Do you want to become part of our community? Here is a simple guide on how to join the server:\n\
  - Take a look at our guide here: [Guide to joining](https://docs.castcrafter.de/how-to-join)\n\
  - You do not need a whitelist for the event server.\n\
  - You need a whitelist for the survival server.\n\n\
   -# We are looking forward to seeing you on the server soon!
how-to-join.en.short=You can find a guide on joining here: https://docs.castcrafter.de/how-to-join (event server without whitelist, survival server with whitelist)

ask.de.short=Stell deine Frage einfach direkt und warte geduldig auf eine Antwort. Frag nicht erst, ob du fragen darfst.
ask.en.question=Just ask directly.
ask.en.long=If you have a question, just ask it. Do not look for specific people or experts. Do not ask whether you may ask a question or whether someone is awake or available. Ask your question directly in the channel and wait patiently for an answer.
ask.en.short=Just ask your question directly and wait patiently for an answer. Do not ask whether you may ask first.

missing-information.de.short=Uns fehlen Informationen: Bitte nenne Server, Koordinaten, Dimension, eine genaue Beschreibung des Problems und den Zeitraum.
missing-information.en.question=Missing information
missing-information.en.long=We are currently still missing some important information to be able to process your request.\n\n\
Please check again whether you have given us all the important information:\n\n\
• **Server** on which it occurred\n\
• **Coordinates** (e.g. `110 64 60`)\n\
• **Dimension** (e.g. `Overworld`)\n\
• **An exact description of the problem**\n\
• **Time period** (e.g. `Yesterday 12:30 to 13:30`)
missing-information.en.short=We are missing information: please provide the server, coordinates, dimension, an exact description of the problem and the time period.

how-to-whitelist.de.short=Für den Survival-Server brauchst du eine aktive Discord-Minecraft Verbindung. Diese kannst du hier einrichten: https://auth.castcrafter.de/account?tab=accounts
how-to-whitelist.en.question=How do I get whitelisted?
how-to-whitelist.en.long=To be able to play on the survival server, instead of a whitelist you need\nan active Discord-Minecraft connection. You can set it up at https://auth.castcrafter.de/account?tab=accounts.\n\nAs soon as both your Discord and your Minecraft account are linked,\nyou can join the survival server. You can check your whitelist status in the \n<#1124438644523012234> channel using the **Check whitelist** button.
how-to-whitelist.en.short=For the survival server you need an active Discord-Minecraft connection. You can set it up here: https://auth.castcrafter.de/account?tab=accounts

ping-pong.de.short=Das Serverteam arbeitet ehrenamtlich und sieht alle Nachrichten und Tickets. Pings beschleunigen nichts, bitte hab etwas Geduld.
ping-pong.en.question=Response times & pings: what you should know!
ping-pong.en.long=Why does the server team not answer immediately?\n\
  - The server team works voluntarily in their free time.\n\
  - We try to help with problems and requests as quickly as possible.\n\
  - Pings are not necessary, the team sees all messages and tickets.\n\
  - Pings do not speed anything up, they can even delay the processing.\n\
  - Please be patient and wait for an answer.\n\n\
  Thank you for your understanding and consideration.
ping-pong.en.short=The server team works voluntarily and sees all messages and tickets. Pings do not speed anything up, please be patient.
