package dev.slne.surf.discord.permission

enum class DiscordPermission {
    COMMAND_TICKET_BUTTONS,

    COMMAND_TICKET_ADD,
    COMMAND_TICKET_REMOVE,

    TICKET_WHITELIST_VIEW,
    TICKET_SUPPORT_SURVIVAL_VIEW,
    TICKET_SUPPORT_EVENT_VIEW,
    TICKET_SUPPORT_DISCORD_VIEW,
    TICKET_REPORT_VIEW,
    TICKET_APPLICATION_VIEW
}