package dev.slne.surf.discord.permission

enum class DiscordPermission {
    UNKNOWN,

    COMMAND_TICKET_BUTTONS,
    COMMAND_ANNOUNCEMENT_CREATE,
    COMMAND_ANNOUNCEMENT_EDIT,
    COMMAND_ANNOUNCEMENT_DELETE,

    COMMAND_TICKET_ADD,
    COMMAND_TICKET_REMOVE,

    TICKET_CLOSE,
    TICKET_CLAIM,

    TICKET_WHITELIST_VIEW,
    TICKET_WHITELIST_CONFIRM,
    TICKET_SUPPORT_SURVIVAL_VIEW,
    TICKET_SUPPORT_EVENT_VIEW,
    TICKET_SUPPORT_DISCORD_VIEW,
    TICKET_REPORT_VIEW,
    TICKET_UNBAN_VIEW,
    TICKET_BUG_VIEW,

    TICKET_APPLICATION_DEVELOPER,
    TICKET_APPLICATION_DESIGNER,
    TICKET_APPLICATION_BUILDER,
    TICKET_APPLICATION_SUPPORTER,
    TICKET_APPLICATION_TWITCH_MODERATOR,
}