package dev.slne.discord.guild.permission

enum class CommandPermission(val permission: String) {
    NO_INTEREST("NO_INTEREST"),
    WHITELIST("WHITELIST"),
    WHITELISTED("WHITELISTED"),
    WHITELIST_QUERY("WHITELIST_QUERY"),
    WHITELIST_ROLE("WHITELIST_ROLE"),
    WHITELIST_UNBLOCK("WHITELIST_UNBLOCK"),
    TICKET_ADD_USER("TICKET_ADD_USER"),
    TICKET_REMOVE_USER("TICKET_REMOVE_USER"),
    TICKET_CLOSE("TICKET_CLOSE"),
    TICKET_BUTTONS("TICKET_BUTTONS"),
}
