package dev.slne.discordold.guild.permission

enum class TicketViewPermission(val permission: String) {
    // Tickets
    VIEW_WHITELIST_TICKETS("VIEW_WHITELIST_TICKETS"),
    VIEW_BUGREPORT_TICKETS("VIEW_BUGREPORT_TICKETS"),
    VIEW_SURVIVAL_SUPPORT_TICKETS("VIEW_SURVIVAL_SUPPORT_TICKETS"),
    VIEW_EVENT_SUPPORT_TICKETS("VIEW_EVENT_SUPPORT_TICKETS"),
    VIEW_DISCORD_SUPPORT_TICKETS("VIEW_DISCORD_SUPPORT_TICKETS"),
    VIEW_UNBAN_TICKETS("VIEW_UNBAN_TICKETS"),
    VIEW_REPORT_TICKETS("VIEW_REPORT_TICKETS"),
    VIEW_APPLICATION_TICKETS("VIEW_APPLICATION_TICKETS"),
}
